ubuntu@ip-172-26-9-152:~/deulbada_BE/config$ sudo nano /etc/systemd/system/daphne_deulbada_BE.service
ubuntu@ip-172-26-9-152:~/deulbada_BE/config$ /home/ubuntu/deulbada_BE/venv/bin/daphne -b 0.0.0.0 -p 8001 config.asgi:application
Traceback (most recent call last):
  File "/home/ubuntu/deulbada_BE/venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 171, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 239, in run
    application = self.load_asgi_app(args.application)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/cli.py", line 208, in load_asgi_app
    return import_by_path(asgi_app_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/deulbada_BE/venv/lib/python3.12/site-packages/daphne/utils.py", line 17, in import_by_path
    target = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'