(venv) PS C:\Users\MIDI-PC\Desktop\backend\250729_final project> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\MIDI-PC\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(**check_kwargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\base.py", line 492, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\checks\registry.py", line 89, in run_checks      
    new_errors = check(app_configs=app_configs, databases=databases)     
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config    
    return check_resolver(resolver)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver      
    return check_method()
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\urls\resolvers.py", line 531, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module       
    return import_module(self.urlconf_name)
  File "C:\Users\MIDI-PC\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import        
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load     
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked      
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\config\urls.py", line 43, in <module>
    path('api/users/', include('users.urls')),
                       ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\MIDI-PC\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import        
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load     
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked      
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\users\urls.py", line 3, in <module>
    from .views import (
    ...<5 lines>...
    )
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\users\views.py", line 13, in <module>
    from .serializers import (
    ...<3 lines>...
    )
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\users\serializers.py", line 8, in <module>
    from posts.models import Post
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\posts\models.py", line 10, in <module>
    class Post(models.Model):
    ...<5 lines>...
        def __str__(self): return f"Post {self.id} by {self.author_id}"  
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\models\base.py", line 136, in __new__
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: Model class posts.models.Post doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.