(venv) PS C:\Users\MIDI-PC\Desktop\backend\250729_final project> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute    
    self.fetch_command(subcommand).run_from_argv(self.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\base.py", line 416, in run_from_argv  
    self.execute(*args, **cmd_options)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\base.py", line 460, in execute        
    output = self.handle(*args, **options)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper        
    res = handle_func(*args, **kwargs)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\core\management\commands\makemigrations.py", line 140, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\migrations\loader.py", line 58, in __init__        
    self.build_graph()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\migrations\loader.py", line 276, in build_graph    
    self.graph.validate_consistency()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\migrations\graph.py", line 198, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
     ~~~~~~~~~~~~~^^
  File "C:\Users\MIDI-PC\Desktop\backend\250729_final project\venv\Lib\site-packages\django\db\migrations\graph.py", line 60, in raise_error      
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration uploads.0002_initial depe